### PR TITLE
1.4.1-1

### PR DESCRIPTION
**Pull request by igavrilov**
Hi Enrique!
I rebased your repo against the latest changes from @djdiskmachine. Not sure if it worth it to create a PR into his fork after.

The main reason I did it, the build for 35xx from @djdiskmachine didn't work on my rg33xx plus (I tried it on muOS). Your solution with [union-rg35xx-toolchain](https://github.com/shauninman/union-rg35xx-toolchain/tree/main) worked pretty well. I didn't play with the app enough yet though however I can tell for sure it works much smoother than the RPi build version.

Also I would like to try out the toolchain from https://github.com/knulli-cfw/toolchains/releases/tag/rg35xx-plush-sdk-20240421 but need to create a docker version for it first.

### CODE REVIEW

**Comment by igavrilov** [comment]
Created this one instead https://github.com/djdiskmachine/LittleGPTracker/pull/96

**Comment by emartinez-dev** [comment]
Hello Ivan!
I am glad that my temporal solution also worked for you. 

Thank you for doing so, I totally forgot to create the merge request on @djdiskmachine fork after compiling and testing it.

I have been playing with LGPT for hours and it has been great so far on my RG35XX-H

**Comment by igavrilov** [comment]
@emartinez-dev alright, seems the build was fine, the problem was in the tempo I used in my project. I tested with 175 BPM, it really becomes laggy after a few seconds of playing even one sample.

**Comment by djdiskmachine** [comment]
Does this mean that the build works fine for XX-H but not so much for XX+ ?

**Pull request closed without merging**
